version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    env_file: .env.production
    ports:
     - "3307:3306"
    volumes:
     - ./mysql:/docker-entrypoint-initdb.d
  
  web:
    image: tomcat:8.5-jre8
    # Environment variables do not appear to be getting loaded the first time Tomcat starts!
    environment:
      JDBC_URL: jdbc:mysql://mysql:3306/motechquartz?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: example_db_user
      JDBC_PASS: example_db_pass
    ports:
     - "8080:8080"
    volumes:
     - ./tomcat/webapps:/usr/local/tomcat/webapps
  
  couchdb:
    image: couchdb:2.1
    restart: always
    volumes:
      - ./couchdb-data-volume:/usr/local/var/lib/couchdb
    env_file: .env.production
    ports:
      - "5985:5984"
      
  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    volumes: ["./activemq-data:/opt/activemq/conf", "./activemq-data:/data/activemq", "./activemq-data:/var/log/activemq"]
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048
      
  postgres:
    image: postgres:9.5
    ports: 
      - "5432:5432"
    volumes: ["./postgres-data:/var/lib/postgresql/data"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      
  metabase:
    image: metabase/metabase:v0.27.2
    ports: 
      - "3000:3000"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password